services:
  - type: web
    name: lendu-php-app
    runtime: docker
    repo: https://github.com/Elvis-pr/lendu
    branch: main
    plan: free
    dockerfilePath: Dockerfile
    RUN echo "DirectoryIndex index.php index.html" > /etc/apache2/conf-enabled/dir.conf

